### ISSUE TITLE
io.netty.handler.codec.EncoderException: us.myles.ViaVersion.exception.InformativeException

### ISSUE THREAD

**Issue by OverBrave** [ViaVersion/ViaVersion#1625]
**Describe the bug, provide any errors**
https://hasteb.in/ozakubiy.kotlin

![image](https://user-images.githubusercontent.com/47111280/72288420-12e25200-365a-11ea-9536-694ddb089412.png)

**ViaVersion Dump:**
https://dump.viaversion.com/1440b2f6d621d1d4184c8a2e37a2402fc7b4004ad05868c98f2de543ab07762a

**Comment by MylesIsCool** [comment]
Can you enable debug=true and repost the error and also provide any extra info about when it happens

**Comment by OverBrave** [comment]
I couldn't find the debug setting in the config file. 
This video: https://streamable.com/tq4ie

**Comment by MylesIsCool** [comment]
It's in server.properties, apologies for missing that bit out

**Comment by KennyTV** [comment]
Try the latest VB build, today and the 9th had some fixes that might be related to your problem.

**Comment by OverBrave** [comment]
https://hasteb.in/kuyaseza.cs

**Comment by OverBrave** [comment]
> Also try the latest VB build, today and the 9th had some fixes that might be related to your problem.

Where can I download?

**Comment by KennyTV** [comment]
https://ci.viaversion.com/view/ViaBackwards/job/ViaBackwards-Abstraction/

**Comment by OverBrave** [comment]
Same problem. And one more problem
![image](https://user-images.githubusercontent.com/47111280/72294328-69ee2400-3666-11ea-89cd-1f7f707001bb.png)

**Comment by KennyTV** [comment]
Alright, fixed in the now latest build 👀 The second issue might be caused by a plugin, but that should go into the ViaBackwards issue tracker eitherway

**Comment by OverBrave** [comment]
Problem not solved. When you closed? Again kicked without plugin. And i updated to #41
![image](https://user-images.githubusercontent.com/47111280/72295078-e46b7380-3667-11ea-8c7b-e2a19cc5d5f9.png)
