### ISSUE TITLE
us.myles.ViaVersion.exception.InformativeException

### ISSUE THREAD

**Issue by MackenzieMolloy** [ViaVersion/ViaVersion#2126]
**Describe the bug, provide any errors**
https://paste.gg/p/anonymous/9128bac9e8b14934bbc8dfa7446cdfdf

Flamecord proxy, 1.8.9 lobby and 1.16.3 sub-server

**How can we reproduce it?**
1. Login on 1.8'
2. once in the lobby, join the 1.16.3 sub-server

...then you get kicked with that error

**Expected behaviour**
You should successfully join the sub-server

**Screenshots**
![image](https://user-images.githubusercontent.com/48184419/95676403-cfe7e780-0bb5-11eb-9c8c-e01e62b04efa.png)

**ViaVersion Dump**
- https://dump.viaversion.com/33309ae06ff484c65c2de34357ce2118509a57c9f351503a2fef12473b926c14

**Additional server info**
FlameCord Proxy, 1.8.9 paperspigot lobby, 1.16.3 sub-servers
ViaVersion/Backwards/Rewind on proxy

**Checklist**
- [x] I have included a Viaversion dump
- [x] If applicable, I have included a paste (not a screenshot) of the error
- [x] I have tried a build from https://ci.viaversion.com/ and the issue still persists

**Comment by KennyTV** [comment]
FlameCord is not supported, please try on a standard Bungee/Waterfall and without other plugins.

**Comment by MackenzieMolloy** [comment]
Aight, sorry about that - switched to Waterfall and the issue is fixed. I'll get in touch with the author of FlameCord to see if they can resolve the issue.

**Comment by MackenzieMolloy** [comment]
A slightly different issue has occured on waterfall...

`[15:08:18 WARN] [ViaBackwards]: Metadata for entity id: 54 not sent because the entity doesn't exist. MetaStorage{metaDataList=[Metadata{id=0, metaType=Byte, value=0}, Metadata{id=2, metaType=OptChat, value=null}, Metadata{id=6, metaType=Pose, value=0}, Metadata{id=4, metaType=Boolean, value=false}, Metadata{id=15, metaType=VarInt, value=6727}, Metadata{id=14, metaType=Float, value=0.0}, Metadata{id=12, metaType=VarInt, value=0}, Metadata{id=13, metaType=OptPosition, value=null}, Metadata{id=8, metaType=Float, value=20.0}, Metadata{id=9, metaType=VarInt, value=0}, Metadata{id=11, metaType=VarInt, value=0}, Metadata{id=10, metaType=Boolean, value=false}, Metadata{id=1, metaType=VarInt, value=300}, Metadata{id=3, metaType=Boolean, value=false}, Metadata{id=7, metaType=Byte, value=0}, Metadata{id=5, metaType=Boolean, value=false}, Metadata{id=16, metaType=Byte, value=127}, Metadata{id=17, metaType=Byte, value=0}, Metadata{id=19, metaType=NBTTag, value=CompoundTag { {} }}, Metadata{id=18, metaType=NBTTag, value=CompoundTag { {} }}]}
>.... [15:08:19 WARN] [ViaBackwards]: Metadata for entity id: 54 not sent because the entity doesn't exist. MetaStorage{metaDataList=[Metadata{id=0, metaType=Byte, value=0}]}`

https://dump.viaversion.com/bcdeb1f041e7dea672076289efca6bcbfcb0185c181e6335b79421c3663f38a5

**Comment by Jo0001** [comment]
That is just a waring.
To fix console spam, use suppress-conversion-warnings: true and suppress-metadata-errors: true in the ViaVersion config.yml. The errors will still happen but you won't be spammed with them and the issues will be ignored.
