### ISSUE TITLE
Sign editor automatically closes with 1.19 on 1.16.5 Paper server

### ISSUE THREAD

**Issue by Phoenix616** [ViaVersion/ViaVersion#2935]
### `/viaversion dump` Output

https://dump.viaversion.com/fd5deb698600ba3a674c58b04aa816e10d0a3984254e9be2ed68f1740b012c0e

### Console Error

None.

### Bug Description

When placing a sign with the 1.19 client the editor instantly closes.

### Steps to Reproduce

1. Install latest [Paper 1.16.5 (794)](https://api.papermc.io/v2/projects/paper/versions/1.16.5/builds/794/downloads/paper-1.16.5-794.jar)
2. Install [ViaVersion 4.3.2-SNAPSHOT build 613](https://ci.viaversion.com/job/ViaVersion/613/artifact/build/libs/ViaVersion-4.3.2-SNAPSHOT.jar) (happens with 4.3.1 release too)
3. Join server and place sign

### Expected Behavior

Sign editor to stay open to edit it.

### Additional Server Info

Works like intended with latest 1.17.1/1.18.2 Paper servers and 1.19 client, and with 1.18.2 client on 1.16.5 server with ViaVersion.

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Paper--794%20%28MC%3A%201.16.5%29](https://img.shields.io/badge/Platform-git--Paper--794%20%28MC%3A%201.16.5%29-3498db?style=flat-square) </br>![ViaVersion (4.3.2-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(4.3.2--SNAPSHOT)-Even%20withmaster-brightgreen?style=flat-square) </br>

**Comment by kennytv** [comment]
Fixed as long as you don't move Via to the proxy

**Comment by turnolos** [comment]
We are still experiencing this issue on the dev build of viaversion.

**Comment by woooferz** [comment]
I'm experiencing the same issue.

**Comment by turnolos** [comment]
@kennytv Would you mind checking this out?

I do not believe the issue is rectified. On our paper 1.12.2 server running the latest dev builds of viaversion, viarewind, and viabackwards. Upon trying to write text to a sign, the editor still automatically closes.

Many thanks, I can provide anything required to help debug this problem.

**Comment by kennytv** [comment]
If you could find out what exact server version this problem starts happening again, that would be great (and open a new issue with a server dump). From quick testing, everything from latest to 1.14.4 is fine, 1.13.2 is not

**Comment by michaello01** [comment]
I wondered what's the reason I can't edit signs. The ack patch not only breaks the signs, but breaks block placing.

**Comment by michaello01** [comment]
@kennytv I noticed what's going on. I increased this delay https://github.com/ViaVersion/ViaVersion/blob/aecef3c3f8db69b26617c9d4a0615e52a5bf0b2f/bukkit/src/main/java/com/viaversion/viaversion/bukkit/providers/BukkitAckSequenceProvider.java#L41
to 20, and sign editing works, after 20 ticks the sign disappear if it can't be placed, but when during these 20 ticks you place a block, then you place a sign, you don't wait 20 ticks to sign to get refreshed, but less. That means ack tasks are not related directly  to the action. I also felt that block placing is better with longer delay. With 20 ticks delay block placing feels great, with smaller delay like 2 or 3 ticks when you place blocks really fast, for example when you place the blocks that touches the block that you just placed, the placing gets blocked and it starts to get really chaotic. Can you check that please? I spent many, many hours investigating that.
