### ISSUE TITLE
1.19 client crashes on kong-painting

### ISSUE THREAD

**Issue by Leahcimkrob** [ViaVersion/ViaVersion#3071]
### `/viaversion dump` Output

https://dump.viaversion.com/4285b564fcc0fddff59ba789663a5f26e71505883198f0f6570c3fa16273e320

### Console Error

https://paste.gg/p/anonymous/572ae7e8a2e74b669a9f8a3a63cbeb26

### Bug Description

Our server is on paper 1.19.1-99. If we pass a Kong painting, the game crashes. I have attached the message. Client-Version 1.18.1, 1.18.1, 1.19. With  Client 1.19.1, we get no error.

### Steps to Reproduce

walk to a kong painting or palce a kong painting

### Expected Behavior

When I'm near a Kong painting, the client crashes

### Additional Server Info

paper-1.19.1-99
Plugins:
https://i.imgur.com/Fb3rdtj.png

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git%3ABungeeCord--Bootstrap%3A1.19--R0.1--SNAPSHOT%3A78ca16d%3A1656](https://img.shields.io/badge/Platform-git%3ABungeeCord--Bootstrap%3A1.19--R0.1--SNAPSHOT%3A78ca16d%3A1656-3498db?style=flat-square) </br>![ViaVersion (4.4.1): 3 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.4.1)-3%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaBackwards(4.4.1): Even with master](https://img.shields.io/badge/ViaBackwards%20(4.4.1)-Even%20with%20master-brightgreen?style=flat-square) </br><br>Please try the **latest** build(s) from [https://ci.viaversion.com/](https://ci.viaversion.com/)

**Comment by kennytv** [comment]
That's not a Via issue

**Comment by Elioby** [comment]
This should be fixed by commit https://github.com/ViaVersion/ViaVersion/commit/9c3395b76b0adb78c51fe8e49b3104c703691064

**Comment by Leahcimkrob** [comment]
With build 631 the game still crashes
new dump: https://dump.viaversion.com/5110ee011c31f453399c11bbee1c6dbe49a85031ac3d6705bf0de6f7de6c1f1b

**Comment by Elioby** [comment]
You need to update your ViaVersion, you're still on commit f9bbb5b1a363b3589cad7dc3ae400e599302b5d0

**Comment by Leahcimkrob** [comment]
we downloaded build 631 from jenckins, stopped the server, deleted the old via version, uploaded the new one and the dump still shows f9bbb5b

https://dump.viaversion.com/5110ee011c31f453399c11bbee1c6dbe49a85031ac3d6705bf0de6f7de6c1f1b

**Comment by Leahcimkrob** [comment]
Ok after another try, this will work. thank you
https://dump.viaversion.com/6d01c198664aa9d2490495537b8937298f7003a9e2b01df3b007f012bab5ee56
