### ISSUE TITLE
[1.18.2 -> 1.19] The /locate command does not work.

### ISSUE THREAD

**Issue by Lolothepro** [ViaVersion/ViaVersion#3331]
### `/viaversion dump` Output

https://dump.viaversion.com/62727ae50296779927669f7b48905175fb4e507c1f2f3939dcba57a405f679c9

### Console Error

```
[CHAT] commands.locate.success
```

### Bug Description

Connect to a 1.18.2 server with a 1.19 client (ViaFabric)
Used the command /locate
The command returns commands.locate.success

### Steps to Reproduce

Connect to a 1.18.2 server with a 1.19 client (ViaFabric)
Used the command /locate
The command returns commands.locate.success

### Expected Behavior

https://user-images.githubusercontent.com/68275908/177345777-3a3349ce-22b6-4c6c-ad3e-c9a2c2248940.mp4

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: 0.4.7+289--main](https://img.shields.io/badge/Platform-0.4.7+289--main-3498db?style=flat-square) </br>![ViaVersion: Outdated](https://img.shields.io/badge/ViaVersion%20(4.4.0--1.19.1--pre2--SNAPSHOT)-Outdated!-red?style=flat-square) </br>![ViaBackwards: Outdated](https://img.shields.io/badge/ViaBackwards%20(4.4.0--1.19.1--pre2--SNAPSHOT)-Outdated!-red?style=flat-square) </br><br><h3>Please update **all** Via* plugins from [https://ci.viaversion.com/](https://ci.viaversion.com/). In case the issue still persists send the new dump and the issue will be reopened</h3>

**Comment by Roadhog360** [comment]
I downloaded VV 4.7.0 a few days ago (I am aware 4.8.0 is now released) and I no longer get this issue with /locatebiome on my 1.16.5 server. This may have been fixed a little while longer, but I wouldn't know as I took a fairly large break recently.

**Comment by HowardZHY** [comment]
Is it still a valid issue?

**Comment by 8MiYile** [comment]
it's still not solve
https://dump.viaversion.com/63ee0a9d51eeeadd0a5668078e889d92c428e123f8320b95978fe8f555d90323
![image](https://github.com/user-attachments/assets/d6fe8363-3347-4ab9-a1cb-9e43f73228d4)

**Comment by Barvalg** [comment]
![Platform: velocity%203.3.0--SNAPSHOT%20%28git--09f687e5--b413%29](https://img.shields.io/badge/Platform-velocity%203.3.0--SNAPSHOT%20%28git--09f687e5--b413%29-3498db?style=flat-square) </br>![Proxy is 17 builds behind](https://img.shields.io/badge/Your%20proxy%20is%2017%20build(s)%20behind.%20Please%20update%20to%20the%20latest%20version-orange?style=flat-square) </br>![ViaVersion (5.0.3): 39 commits behind master](https://img.shields.io/badge/ViaVersion%20(5.0.3)-39%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaRewind(4.0.2): 8 commits behind master](https://img.shields.io/badge/ViaRewind%20(4.0.2)-8%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaBackwards(5.0.3): 23 commits behind master](https://img.shields.io/badge/ViaBackwards%20(5.0.3)-23%20commit(s)%20behind%20master-yellow?style=flat-square) </br><br><h3>Please update **all** Via* plugins from [https://ci.viaversion.com/](https://ci.viaversion.com/).In case the issue still persists send the new dump </h3>

**Comment by 8MiYile** [comment]
@kennytv need open this ticket
