### ISSUE TITLE
Cannot connect with Java Edition Version <1.20.2

### ISSUE THREAD

**Issue by EpicJosch** [ViaVersion/ViaVersion#3462]
### `/viaversion dump` Output

https://dump.viaversion.com/537a6ff3a644676e91d47978ff1a45be7c7a67a90894c3045240ee872ae6fcd2

### Console Error

No errors in console

### Bug Description

When i connect with Java Edition V. 1.20.2 everything works fine. But when i try to connect with V. 1.20.1 i get an Internal Exception: DecoderException and i can't join the server. I am running ViaVersion 4.8.0 and Paper 1.20.1 Build #196. Also im using the latest versions and builds from ViaBackwards, GeyserMC and Floodgate

### Steps to Reproduce

1. Login with 1.20.1 Client

### Expected Behavior

- Beeing able to join with every version supported by via version and via backwards

### Additional Server Info

I am also using waterfall with ViaVersion, ViaBackwards, Geyser MC and Floodgate installed.

Everything worked fine until i updated waterfall and paper to the latest build. Then this error started occuring.

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Paper--196%20%28MC%3A%201.20.1%29](https://img.shields.io/badge/Platform-git--Paper--196%20%28MC%3A%201.20.1%29-3498db?style=flat-square) </br>![ViaVersion (4.8.0): 18 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.8.0)-18%20commit(s)%20behind%20master-yellow?style=flat-square) </br><br><h3>Please try the **latest** build(s) from [https://ci.viaversion.com/](https://ci.viaversion.com/). In case the issue still persists send the new dump</h3>

**Comment by kennytv** [comment]
Updating to ci builds should fix the issue

**Comment by EpicJosch** [comment]
No. Still doesnt work on development version. Same issue. New Dump: https://dump.viaversion.com/f48fce9519caf920a79ac70494e786a65339971c0a66eadb6bbdff7bcb91bab9

**Comment by Barvalg** [comment]
![Platform: git--Paper--196%20%28MC%3A%201.20.1%29](https://img.shields.io/badge/Platform-git--Paper--196%20%28MC%3A%201.20.1%29-3498db?style=flat-square) </br>![ViaVersion (4.8.1-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(4.8.1--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaBackwards(4.8.1-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaBackwards%20(4.8.1--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>
