### ISSUE TITLE
Equippable allowed_entities causes kick

### ISSUE THREAD

**Issue by DarkChromaMC** [ViaVersion/ViaVersion#4567]
### `/viaversion dump` Output

https://dump.viaversion.com/aead33eb5ce1d18f361994316d68b4d157ad72b0eab02b2b65e95f1d205db535

### Server/Client Error

```
https://mclo.gs/4dYpyje
```

### Bug Description

The Minecraft game crashes for 1.21.4 when a player receives or interacts with an item that uses the equippable tag and has allowed_entities set to only ["minecraft:player"].

### Steps to Reproduce

Steps to Reproduce:
	1.	Launch Minecraft 1.21.4 and enter the server.
	2.	Run the following command:

/give @p minecraft:paper{equippable:{slot:"head",allowed_entities:["minecraft:player"]}}

	3.	Notice you get immediately kicked and crash anyone near you.

### Expected Behavior

The item does not crash the user or nearby players.

### Checklist

- [x] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. Velocity), **not on both**.
- [x] I have included a ViaVersion dump.
- [x] If applicable, I have included a paste (**not a screenshot**) of the error.
- [x] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: 1.21.7--DEV--23d55ff%20%28MC%3A%201.21.7%29](https://img.shields.io/badge/Platform-1.21.7--DEV--23d55ff%20%28MC%3A%201.21.7%29-3498db?style=flat-square) </br>![ViaVersion (5.4.2-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(5.4.2--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaBackwards(5.4.1): Even with master](https://img.shields.io/badge/ViaBackwards%20(5.4.1)-Even%20with%20master-brightgreen?style=flat-square) </br>

### [Athena Log Analysis](https://mclo.gs/4dYpyje)
 #### Platform Information:
| **Property**       | **Details**     |
|--------------------|-----------------|
| Contains Via    | :x:          |
| Platform Type  | `Client (vanilla or modded)`    |
| Is Proxy        | :x:          |

**Comment by kennytv** [comment]
Cannot reproduce on a clean 1.21.7 Paper server with a 1.21.4 client (though I had to fix the command you provided to `/give @p paper[equippable={slot:"head",allowed_entities:["minecraft:player"]}]`)

**Comment by DarkChromaMC** [comment]
This is the crash report I get:
https://mclo.gs/cHxvQwJ

**Comment by DarkChromaMC** [comment]
I tested on a completely fresh paper 1.21.7 server with just viaversion and viabackwards installed. This is a spark profile: https://spark.lucko.me/4vTbz4icXh

`This server is running Paper version 1.21.7-16-main@6e598f8 (2025-07-03T19:49:41Z) (Implementing API version 1.21.7-R0.1-SNAPSHOT)
You are running the latest version`

https://youtu.be/ZL7V6zNZ4a8

**Comment by kennytv** [comment]
Thanks, fixed now

**Comment by DarkChromaMC** [comment]
Hey @kennytv, I tried the latest viaversion 5.4.2-SNAPSHOT released about 55 minutes ago, and the error still occurs unfortunately. No console errors but client crashes with this:

[disconnect-2025-07-05_04.11.03-client.txt](https://github.com/user-attachments/files/21061415/disconnect-2025-07-05_04.11.03-client.txt)

**Comment by kennytv** [comment]
Uhh can you send a new dump?

**Comment by DarkChromaMC** [comment]
https://dump.viaversion.com/e7f930d33cdfa7fecea24e265438d6effd91a9b2a6996d4009644987c513970e

**Comment by Barvalg** [comment]
![Platform: 1.21.7--DEV--23d55ff%20%28MC%3A%201.21.7%29](https://img.shields.io/badge/Platform-1.21.7--DEV--23d55ff%20%28MC%3A%201.21.7%29-3498db?style=flat-square) </br>![ViaVersion (5.4.2-SNAPSHOT): 1 commits behind master](https://img.shields.io/badge/ViaVersion%20(5.4.2--SNAPSHOT)-1%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaBackwards(5.4.1): Even with master](https://img.shields.io/badge/ViaBackwards%20(5.4.1)-Even%20with%20master-brightgreen?style=flat-square) </br><br><h3>Please update **all** Via* plugins from [https://ci.viaversion.com/](https://ci.viaversion.com/).In case the issue still persists send the new dump and the issue will be reopened</h3>

**Comment by DarkChromaMC** [comment]
These were the viaversion debug logs when joining the server: https://mclo.gs/iQ61fB0

**Comment by kennytv** [comment]
You don't have the latest version, could be from jenkins main page caching. see https://ci.viaversion.com/job/ViaVersion/1182/

**Comment by DarkChromaMC** [comment]
I just compiled the plugin myself and the jar worked! Was this the correct place to download future dev jars? https://ci.viaversion.com/job/ViaVersion/

**Comment by DarkChromaMC** [comment]
Ah okay, that makes sense. Thanks for your help!
