### ISSUE TITLE
[1.21.1->1.21.8] Output appears as ghost item when trading with a villager buying an itemstack with custom attributes

### ISSUE THREAD

**Issue by chaossafti** [ViaVersion/ViaVersion#4727]
### `/viaversion dump` Output

https://dump.viaversion.com/673094af991afb76accb8686b314950db3ca120ad785a6f22f93b0056f97a546

### Server/Client Error

No errors appear in console or the client.

### Bug Description

Trading with a villager on a 1.21.1 client connected to a 1.21.8 server causes the output slot to appear as a ghost item.
This only happens for when either of the bought items have a custom attribute data component.

https://github.com/user-attachments/assets/47d8af43-d674-4623-973a-5c3086320590

### Steps to Reproduce

1. Log into the server using 1.21.1
2. Create a villager (shopkeepers plugin or commands) buying an item with custom attributes
3. Try trading in survival mode by clicking the trade
4. The output slot stays air and does not appear

### Additional Server Info

Im using viaversion, viabackwards and the shopkeepers plugin to replicate this on a freshly installed 1.21.8 paper server.

### Checklist

- [x] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. Velocity), **not on both**.
- [x] I have included a ViaVersion dump.
- [x] If applicable, I have included a paste (**not a screenshot**) of the error.
- [x] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: 1.21.8--60--29c8822%20(MC:%201.21.8)](https://img.shields.io/badge/Platform-1.21.8--60--29c8822%20(MC:%201.21.8)-3498db?style=flat-square) </br>![ViaVersion (5.5.2-SNAPSHOT): Error fetching commit data](https://img.shields.io/badge/ViaVersion%20(5.5.2--SNAPSHOT)-Error%20fetching%20commit%20data-lightgray?style=flat-square) </br>![ViaBackwards(5.5.2-SNAPSHOT): 1 commits behind master](https://img.shields.io/badge/ViaBackwards%20(5.5.2--SNAPSHOT)-1%20commit(s)%20behind%20master-yellow?style=flat-square) </br>
### Please update all Via* plugins from https://ci.viaversion.com/ .In case the issue still persists send the new dump and the issue will be reopened


### Athena Log Analysis
 #### Platform Information:
| **Property** | **Details**     |
|--------------|-----------------|
| Contains Via | :x:          |
| Platform Type| `unknown`    |
| Is Proxy     | :x:          |

**Comment by chaossafti** [comment]
Updated dump: https://dump.viaversion.com/7e7db22fe02683fd1f0d431d307e9fb7134a2274e3ed67e82b7d091a63ee378a
The issue persists the same way.

**Comment by Barvalg** [comment]
![Platform: 1.21.8--60--29c8822%20(MC:%201.21.8)](https://img.shields.io/badge/Platform-1.21.8--60--29c8822%20(MC:%201.21.8)-3498db?style=flat-square) </br>![ViaVersion (5.5.2-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(5.5.2--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaBackwards(5.5.2-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaBackwards%20(5.5.2--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>

**Comment by noaskers** [comment]
Has been happing to me as well since 1.21.11 update.

**Comment by kennytv** [comment]
I fixed an issue with player profile hashing. If there are others, please open a new issue and paste the item / villager trade contents

**Comment by ikuria** [comment]
[summon paste](https://pastebin.com/raw/sAn5GcNw)
still occurs

**Comment by kennytv** [comment]
Fully fixed with https://github.com/ViaVersion/ViaVersion/commit/1f40811877827e813f2c0b2c944fa0c934341820
